# Generated by Django 5.1.7 on 2025-05-01 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('generos', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('companias', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('calificacion', models.FloatField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.FloatField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'juego')},
            },
        ),
        migrations.CreateModel(
            name='UserTagJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'juego', 'tag')},
            },
        ),
    ]
