# Generated by Django 5.1.7 on 2025-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='sistema_operativo',
            field=models.CharField(default='2000-01-01', max_length=100),
            preserve_default=False,
        ),
    ]
